// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fetch from "bs-fetch/src/Fetch.res.mjs";
import * as React from "react";
import * as SolverIndex from "./components/Solver/SolverIndex.res.mjs";
import * as SudokuIndex from "./components/Sudoku/SudokuIndex.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return "sudoku";
      });
  var setActiveTab = match[1];
  var activeTab = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setBackendMessage = match$1[1];
  var backendMessage = match$1[0];
  var testBackendConnection = function () {
    fetch("/api/backend/hello").then(function (response) {
            return Fetch.$$Response.text(response);
          }).then(function (message) {
          setBackendMessage(function (param) {
                return message;
              });
          return Promise.resolve();
        });
  };
  var tmp;
  switch (activeTab) {
    case "sat" :
        tmp = JsxRuntime.jsx(SolverIndex.make, {
              tabName: "sat"
            });
        break;
    case "smt" :
        tmp = JsxRuntime.jsx(SolverIndex.make, {
              tabName: "smt"
            });
        break;
    case "sudoku" :
        tmp = JsxRuntime.jsx(SudokuIndex.make, {});
        break;
    default:
      tmp = null;
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Logic Solver Playground🛝",
                      className: "text-3xl font-semibold mb-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Test Backend Connection",
                              className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded",
                              onClick: (function (param) {
                                  testBackendConnection();
                                })
                            }),
                        backendMessage !== "" ? JsxRuntime.jsx("div", {
                                children: backendMessage,
                                className: "mt-2 p-2 bg-gray-100 rounded"
                              }) : null
                      ],
                      className: "mb-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Sudoku Solver",
                              className: "py-2 px-4 " + (
                                activeTab === "sudoku" ? "border-b-2 border-blue-500 font-semibold" : ""
                              ),
                              onClick: (function (param) {
                                  setActiveTab(function (param) {
                                        return "sudoku";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "SAT Solver",
                              className: "py-2 px-4 " + (
                                activeTab === "sat" ? "border-b-2 border-blue-500 font-semibold" : ""
                              ),
                              onClick: (function (param) {
                                  setActiveTab(function (param) {
                                        return "sat";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "SMT Solver",
                              className: "py-2 px-4 " + (
                                activeTab === "smt" ? "border-b-2 border-blue-500 font-semibold" : ""
                              ),
                              onClick: (function (param) {
                                  setActiveTab(function (param) {
                                        return "smt";
                                      });
                                })
                            })
                      ],
                      className: "flex space-x-4 mb-6 border-b"
                    }),
                JsxRuntime.jsx("div", {
                      children: tmp,
                      className: "mt-4"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
