// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactToastify from "react-toastify";

function success(message) {
  ReactToastify.toast.success(message);
}

function error(message) {
  ReactToastify.toast.error(message);
}

function info(message) {
  ReactToastify.toast.info(message);
}

function warning(message) {
  ReactToastify.toast.warning(message);
}

export {
  success ,
  error ,
  info ,
  warning ,
}
/* react-toastify Not a pure module */
