version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - HOST=0.0.0.0
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5170:"
    volumes:
      - ./backend:/app/backend
