
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - ./backend:/app/backend

networks:
  default:
    driver: bridge
