// Generated by ReScript, PLEASE EDIT WITH CARE


function logRequest(api) {
  console.log(api.message + "\n", JSON.stringify(api.data));
}

function logResponse(api) {
  var match = api.status;
  var status = match === "success" ? "success" : "error";
  console.log(api.message + "\n" + status + "\n", JSON.stringify(api.data));
}

export {
  logRequest ,
  logResponse ,
}
/* No side effect */
