// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function sudokuGenerate() {
  return fetch("/api/sudoku/generate", {
                method: "GET"
              }).then(function (response) {
              if (response.ok) {
                return response.json();
              } else {
                return Promise.reject(Js_exn.raiseError("Network response was not ok"));
              }
            });
}

export {
  sudokuGenerate ,
}
/* No side effect */
