// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ToastContext from "../components/Toast/ToastContext.res.mjs";

function logRequest(api) {
  console.log(api.message + "\n", JSON.stringify(api.data));
}

function logResponse(api) {
  var match = api.status;
  var status = match === "success" ? "success" : "error";
  console.log(api.message + "\n" + status + "\n", JSON.stringify(api.data));
}

function generateId() {
  return Date.now().toString();
}

function useToast() {
  var context = React.useContext(ToastContext.context);
  var showToast = function (message, toastType) {
    context.dispatch({
          TAG: "AddToast",
          _0: {
            id: Date.now().toString(),
            message: message,
            toastType: toastType
          }
        });
  };
  return {
          success: (function (message) {
              showToast(message, "success");
            }),
          error: (function (message) {
              showToast(message, "error");
            }),
          info: (function (message) {
              showToast(message, "info");
            })
        };
}

export {
  logRequest ,
  logResponse ,
  generateId ,
  useToast ,
}
/* react Not a pure module */
