// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";

async function makeRequest(url) {
  var response = await fetch(url);
  var json = await response.json();
  console.log(json);
}

function connectToBackend() {
  Core__Promise.$$catch(makeRequest("http://localhost:8080/backend/hello").then(function (response) {
            console.log(response);
            return Promise.resolve();
          }), (function (error) {
          console.log("Error:", error);
          return Promise.resolve();
        }));
}

export {
  makeRequest ,
  connectToBackend ,
}
/* No side effect */
