// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Toast(props) {
  var onClose = props.onClose;
  var toastType = props.toastType;
  var bgColor = toastType === "error" ? "bg-red-500" : (
      toastType === "success" ? "bg-green-500" : "bg-blue-500"
    );
  var icon = toastType === "error" ? "✕" : (
      toastType === "success" ? "✓" : "ℹ"
    );
  React.useEffect((function () {
          var timeoutId = setTimeout((function () {
                  onClose();
                }), 3000);
          return (function () {
                    clearTimeout(timeoutId);
                  });
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: icon,
                      className: "mr-2"
                    }),
                JsxRuntime.jsx("span", {
                      children: props.message
                    })
              ],
              className: "fixed bottom-4 right-4 flex items-center p-4 text-white rounded-lg shadow-lg " + bgColor
            });
}

var make = Toast;

export {
  make ,
}
/* react Not a pure module */
