// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Grid(props) {
  var size = props.size;
  var subGridSize;
  switch (size) {
    case 4 :
    case 6 :
        subGridSize = 2;
        break;
    default:
      subGridSize = 3;
  }
  var cellStyle = "w-10 h-10 border border-gray-300 flex items-center justify-center";
  var thickBorderStyle = "border-2 border-gray-800";
  return JsxRuntime.jsx("div", {
              children: Core__Array.make(size, 0).map(function (rowIndex, param) {
                    return JsxRuntime.jsx("div", {
                                children: Core__Array.make(size, 0).map(function (colIndex, param) {
                                      var isRightBorder = Caml_int32.mod_(colIndex + 1 | 0, subGridSize) === 0 && colIndex !== (size - 1 | 0);
                                      var isBottomBorder = Caml_int32.mod_(rowIndex + 1 | 0, subGridSize) === 0 && rowIndex !== (size - 1 | 0);
                                      var borderStyles = isRightBorder ? (
                                          isBottomBorder ? cellStyle + " border-r-" + thickBorderStyle + " border-b-" + thickBorderStyle : cellStyle + " border-r-" + thickBorderStyle
                                        ) : (
                                          isBottomBorder ? cellStyle + " border-b-" + thickBorderStyle : cellStyle
                                        );
                                      return JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("input", {
                                                        className: "w-full h-full text-center focus:outline-none",
                                                        maxLength: 1,
                                                        pattern: "[1-9]*",
                                                        type: "text",
                                                        onInput: (function (param) {
                                                            
                                                          })
                                                      }),
                                                  className: borderStyles
                                                }, rowIndex.toString() + "-" + colIndex.toString());
                                    }),
                                className: "flex"
                              }, rowIndex.toString());
                  }),
              className: "grid gap-0"
            });
}

var make = Grid;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
