// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.res.mjs";
import * as React from "react";
import * as Button from "../Button/Button.res.mjs";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SudokuIndex(props) {
  var match = React.useState(function () {
        return 9;
      });
  var setGridSize = match[1];
  var gridSize = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Sudoku Grid"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsxs("select", {
                                            children: [
                                              JsxRuntime.jsx("option", {
                                                    children: "4x4",
                                                    value: "4"
                                                  }),
                                              JsxRuntime.jsx("option", {
                                                    children: "6x6",
                                                    value: "6"
                                                  }),
                                              JsxRuntime.jsx("option", {
                                                    children: "9x9",
                                                    value: "9"
                                                  })
                                            ],
                                            className: "border border-gray-300 rounded px-2 py-1",
                                            value: gridSize.toString(),
                                            onChange: (function ($$event) {
                                                var newSize = Core__Option.getOr(Core__Int.fromString($$event.target.value, undefined), 9);
                                                setGridSize(function (param) {
                                                      return newSize;
                                                    });
                                              })
                                          }),
                                      className: "flex items-center gap-2 ml-2"
                                    })
                              ],
                              className: "text-xl font-semibold mb-4 justify-start flex items-center"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(Grid.make, {
                                    size: gridSize
                                  }),
                              className: "border-2 border-gray-300 p-4 justify-center flex"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Controls",
                              className: "text-xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Button.make, {
                                      children: "Solve Puzzle",
                                      onClick: (function (param) {
                                          
                                        })
                                    }),
                                JsxRuntime.jsx(Button.make, {
                                      children: "Clear Grid",
                                      onClick: (function (param) {
                                          
                                        })
                                    }),
                                JsxRuntime.jsx(Button.make, {
                                      children: "Generate New Puzzle",
                                      onClick: (function (param) {
                                          
                                        })
                                    })
                              ],
                              className: "space-y-4"
                            })
                      ]
                    })
              ],
              className: "grid grid-cols-2 gap-6"
            });
}

var make = SudokuIndex;

export {
  make ,
}
/* Grid Not a pure module */
