// Generated by ReScript, PLEASE EDIT WITH CARE


function positionToString(position) {
  if (position === "bottomRight") {
    return "bottom-right";
  } else if (position === "topLeft") {
    return "top-left";
  } else if (position === "bottomCenter") {
    return "bottom-center";
  } else if (position === "bottomLeft") {
    return "bottom-left";
  } else if (position === "topRight") {
    return "top-right";
  } else {
    return "top-center";
  }
}

export {
  positionToString ,
}
/* No side effect */
